//! Isolated MySQL tests for the default-off external identity mapping tables.
//!
//! These tests never run migrations, create/drop schema objects, or clean up
//! existing rows. They run only against an explicitly named isolated database
//! whose name is supplied in `INTEGRATION_IDENTITY_MAPPING_TEST_DATABASE` and
//! matches the `sdk_identity_mapping_test_` allow-prefix. Before running writes,
//! opt in with `RUST_INTEGRATION_REQUIRED=1` and `DATABASE_URL`; any missing or
//! invalid prerequisite fails (there is no implicit [SKIP] path).
//!
//! Run with:
//! `RUST_INTEGRATION_REQUIRED=1 DATABASE_URL=... INTEGRATION_IDENTITY_MAPPING_TEST_DATABASE=sdk_identity_mapping_test_<run> cargo test -p astral-db --test integration_identity_mapping -- --ignored`

use astral_db::{
    create_integration_identity_mapping, read_integration_identity_mapping,
    set_integration_identity_mapping_status, validate_integration_mapping_schema,
    CreateIntegrationIdentityMapping, IntegrationIdentityKey, IntegrationIdentityMappingStatus,
    SetIntegrationIdentityMappingStatus,
};
use sqlx::mysql::{MySqlConnectOptions, MySqlPoolOptions};
use sqlx::MySqlPool;
use std::str::FromStr;
use uuid::Uuid;

async fn required_test_pool() -> MySqlPool {
    assert_eq!(
        std::env::var("RUST_INTEGRATION_REQUIRED").as_deref(),
        Ok("1"),
        "set RUST_INTEGRATION_REQUIRED=1 to opt into this destructive-isolation-gated test"
    );
    let url = std::env::var("DATABASE_URL")
        .ok()
        .filter(|value| !value.trim().is_empty())
        .expect("DATABASE_URL must be set when RUST_INTEGRATION_REQUIRED=1");
    let expected_database = std::env::var("INTEGRATION_IDENTITY_MAPPING_TEST_DATABASE")
        .expect("isolated database name must be explicitly configured");
    assert!(
        expected_database.starts_with("sdk_identity_mapping_test_"),
        "test database name must begin with sdk_identity_mapping_test_"
    );
    let options = MySqlConnectOptions::from_str(&url).expect("DATABASE_URL must parse");
    let actual_database = options
        .get_database()
        .expect("DATABASE_URL must select a named database");
    assert_eq!(actual_database, expected_database);
    assert_ne!(actual_database, "mysql");
    assert_ne!(actual_database, "test");
    let pool = MySqlPoolOptions::new()
        .max_connections(4)
        .connect_with(options)
        .await
        .expect("required MySQL connection must succeed");
    validate_integration_mapping_schema(&pool)
        .await
        .expect("the isolated test database must be manually migrated before tests");
    pool
}

async fn create_test_identity(pool: &MySqlPool) -> (i64, i64) {
    let salt = Uuid::new_v4().simple().to_string();
    let user_no = format!("sdk-test-{salt}");
    let mut transaction = pool
        .begin()
        .await
        .expect("begin isolated fixture transaction");
    let user_id: i64 = sqlx::query(
        "INSERT INTO platform_user (user_no, display_name, source_type, status) \
         VALUES (?, 'SDK mapping integration test', 'LOCAL', 'ACTIVE')",
    )
    .bind(user_no)
    .execute(&mut *transaction)
    .await
    .expect("insert isolated platform user")
    .last_insert_id() as i64;
    let identity_card_id: i64 = sqlx::query(
        "INSERT INTO identity_card (user_id, status, token_version) \
         VALUES (?, 'ACTIVE', 1)",
    )
    .bind(user_id)
    .execute(&mut *transaction)
    .await
    .expect("insert isolated active identity card")
    .last_insert_id() as i64;
    sqlx::query("INSERT INTO identity_global_admin (user_id, status) VALUES (?, 'ACTIVE')")
        .bind(user_id)
        .execute(&mut *transaction)
        .await
        .expect("create exact test administrator");
    transaction
        .commit()
        .await
        .expect("commit isolated test identity");
    (user_id, identity_card_id)
}

async fn cleanup_test_namespace(
    pool: &MySqlPool,
    app_id: &[u8],
    _issuer: &[u8],
    _subject: &[u8],
    user_id: i64,
    identity_card_id: i64,
) {
    // These exact keys are generated by this test with an unpredictable salt.
    // Cleanup is deliberately restricted to its unique app namespace and user.
    sqlx::query(
        "DELETE FROM audit_log WHERE event_type = 'IDENTITY_INTEGRATION_MAPPING' AND user_id = ?",
    )
    .bind(user_id)
    .execute(pool)
    .await
    .expect("clean isolated mapping audit entries");
    sqlx::query("DELETE FROM integration_identity_mapping_operation WHERE actor_id = ?")
        .bind(user_id)
        .execute(pool)
        .await
        .expect("clean isolated operation entries");
    sqlx::query(
        "DELETE FROM integration_identity_mapping \
         WHERE app_id = ? AND user_id = ? AND identity_card_id = ?",
    )
    .bind(app_id)
    .bind(user_id)
    .bind(identity_card_id)
    .execute(pool)
    .await
    .expect("clean exact external mapping key");
    sqlx::query("DELETE FROM identity_global_admin WHERE user_id = ?")
        .bind(user_id)
        .execute(pool)
        .await
        .expect("clean exact test administrator");
    sqlx::query("DELETE FROM identity_card WHERE card_id = ? AND user_id = ?")
        .bind(identity_card_id)
        .bind(user_id)
        .execute(pool)
        .await
        .expect("clean exact test identity card");
    sqlx::query("DELETE FROM platform_user WHERE user_id = ?")
        .bind(user_id)
        .execute(pool)
        .await
        .expect("clean exact test platform user");
}

#[tokio::test]
#[ignore = "requires a manually prepared isolated MySQL database with this migration applied"]
async fn create_read_idempotency_cas_revoke_and_permanent_key_ownership() {
    let pool = required_test_pool().await;
    let salt = Uuid::new_v4().simple().to_string();
    let app_id = format!("sdk-test-{salt}");
    let issuer = format!("Issuer/{salt}");
    let subject = format!("Subject/{salt}");
    let create_operation = format!("sdk-test-{salt}-create");
    let disable_operation = format!("sdk-test-{salt}-disable");
    let revoke_operation = format!("sdk-test-{salt}-revoke");
    let key = IntegrationIdentityKey::new(&app_id, &issuer, &subject).unwrap();
    let (user_id, identity_card_id) = create_test_identity(&pool).await;

    let case_pool = pool.clone();
    let case_app = app_id.clone();
    let case_issuer = issuer.clone();
    let case_subject = subject.clone();
    let result = tokio::spawn(async move {
        let pool = case_pool;
        let app_id = case_app;
        let issuer = case_issuer;
        let subject = case_subject;
        let create = CreateIntegrationIdentityMapping {
            key: key.clone(),
            user_id,
            identity_card_id,
            operation_id: create_operation.clone(),
            actor_id: user_id,
        };
        assert_eq!(
            create_integration_identity_mapping(&pool, create.clone())
                .await
                .unwrap(),
            1
        );
        assert_eq!(
            create_integration_identity_mapping(&pool, create.clone())
                .await
                .unwrap(),
            1
        );
        let mut changed_replay = create.clone();
        changed_replay.identity_card_id += 1;
        assert!(create_integration_identity_mapping(&pool, changed_replay)
            .await
            .is_err());

        let read = read_integration_identity_mapping(&pool, &key)
            .await
            .unwrap()
            .expect("active mapping should resolve to its source identity");
        assert_eq!(read.user_id, user_id);
        assert_eq!(read.identity_card_id, identity_card_id);
        assert_eq!(read.revision, 1);

        assert_eq!(
            set_integration_identity_mapping_status(
                &pool,
                SetIntegrationIdentityMappingStatus {
                    key: key.clone(),
                    expected_revision: 1,
                    status: IntegrationIdentityMappingStatus::Disabled,
                    operation_id: disable_operation.clone(),
                    actor_id: user_id,
                },
            )
            .await
            .unwrap(),
            2
        );
        assert!(read_integration_identity_mapping(&pool, &key)
            .await
            .unwrap()
            .is_none());

        let wrong_revision = SetIntegrationIdentityMappingStatus {
            key: key.clone(),
            expected_revision: 1,
            status: IntegrationIdentityMappingStatus::Revoked,
            operation_id: format!("sdk-test-{salt}-wrong-cas"),
            actor_id: user_id,
        };
        assert!(
            set_integration_identity_mapping_status(&pool, wrong_revision)
                .await
                .is_err()
        );

        assert_eq!(
            set_integration_identity_mapping_status(
                &pool,
                SetIntegrationIdentityMappingStatus {
                    key: key.clone(),
                    expected_revision: 2,
                    status: IntegrationIdentityMappingStatus::Revoked,
                    operation_id: revoke_operation.clone(),
                    actor_id: user_id,
                },
            )
            .await
            .unwrap(),
            3
        );
        assert!(read_integration_identity_mapping(&pool, &key)
            .await
            .unwrap()
            .is_none());

        let cannot_rebind = CreateIntegrationIdentityMapping {
            key: key.clone(),
            user_id,
            identity_card_id,
            operation_id: format!("sdk-test-{salt}-rebind"),
            actor_id: user_id,
        };
        assert!(create_integration_identity_mapping(&pool, cannot_rebind)
            .await
            .is_err());

        let distinct_case_key =
            IntegrationIdentityKey::new(&app_id, &issuer.to_uppercase(), &subject).unwrap();
        let case_create = CreateIntegrationIdentityMapping {
            key: distinct_case_key.clone(),
            user_id,
            identity_card_id,
            operation_id: format!("sdk-test-{salt}-case-create"),
            actor_id: user_id,
        };
        assert_eq!(
            create_integration_identity_mapping(&pool, case_create)
                .await
                .unwrap(),
            1
        );
        assert!(read_integration_identity_mapping(&pool, &distinct_case_key)
            .await
            .unwrap()
            .is_some());
    })
    .await;

    cleanup_test_namespace(
        &pool,
        app_id.as_bytes(),
        issuer.as_bytes(),
        subject.as_bytes(),
        user_id,
        identity_card_id,
    )
    .await;
    pool.close().await;
    if let Err(error) = result {
        if error.is_panic() {
            std::panic::resume_unwind(error.into_panic());
        }
        panic!("isolated fixture runner interrupted: {error}");
    }
}

#[tokio::test]
#[ignore = "requires a manually prepared isolated MySQL database with this migration applied"]
async fn mapping_read_rejects_inactive_or_expired_source_identity() {
    let pool = required_test_pool().await;
    let salt = Uuid::new_v4().simple().to_string();
    let app_id = format!("sdk-test-{salt}");
    let issuer = format!("issuer-{salt}");
    let subject = format!("subject-{salt}");
    let key = IntegrationIdentityKey::new(&app_id, &issuer, &subject).unwrap();
    let (user_id, identity_card_id) = create_test_identity(&pool).await;
    let create_operation = format!("sdk-test-{salt}-create");
    let case_pool = pool.clone();
    let result = tokio::spawn(async move {
        let pool = case_pool;
        assert_eq!(
        create_integration_identity_mapping(
            &pool,
            CreateIntegrationIdentityMapping {
                key: key.clone(),
                user_id,
                identity_card_id,
                operation_id: create_operation.clone(),
                actor_id: user_id,
            },
        )
        .await
        .unwrap(),
        1
    );
    assert!(read_integration_identity_mapping(&pool, &key)
        .await
        .unwrap()
        .is_some());

    sqlx::query("UPDATE identity_card SET expires_at = DATE_SUB(UTC_TIMESTAMP(), INTERVAL 1 DAY) WHERE card_id = ?")
        .bind(identity_card_id)
        .execute(&pool)
        .await
        .expect("expire the isolated test card");
    assert!(read_integration_identity_mapping(&pool, &key)
        .await
        .unwrap()
        .is_none());
    }).await;
    cleanup_test_namespace(
        &pool,
        app_id.as_bytes(),
        issuer.as_bytes(),
        subject.as_bytes(),
        user_id,
        identity_card_id,
    )
    .await;
    pool.close().await;
    if let Err(error) = result {
        if error.is_panic() {
            std::panic::resume_unwind(error.into_panic());
        }
        panic!("isolated fixture runner interrupted: {error}");
    }
}
