[package]
name = "astral-common"
version = "0.1.0"
edition = "2021"
description = "AstralLight 公共基础设施（配置、错误、中间件）"
license.workspace = true

[features]
e3-observability = []
e4-observability = []

[dependencies]
astral-types = { path = "../astral-types" }

axum = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
config = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
time = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
async-trait = "0.1"
jsonwebtoken = { workspace = true }
futures-util = "0.3"
policy-engine = { path = "../policy-engine" }
hmac = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
ed25519-dalek = { workspace = true }
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
serde_json = { workspace = true }
rand = "0.8"
rsa = { version = "0.9", features = ["pem"] }
