[package]
name = "astral-learn-sdk-sample"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
publish = false

[dependencies]
astral-sdk-contracts = { workspace = true }
astral-sdk = { workspace = true }
sha2 = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
astral-sdk-test-support = { path = "../test-support" }
astral-sdk-axum = { workspace = true }
axum = { workspace = true }
tower = { version = "0.5", features = ["util"] }
tokio = { workspace = true }
ed25519-dalek = { workspace = true }
